### Hello
GET http://localhost:3000/

### Create transaction
POST http://localhost:3000/transactions
Content-Type: application/json

{
    "amount": 20,
    "type": "withdrawal",
    "accountNumber": "2"
}

### Get account balance
GET http://localhost:3000/accounts/2