## spin up postgres 
version: "3.8"

services:
  pg:
    image: postgres:14.5
    container_name: nestjs_pg
    restart: always
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5436:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo:
    image: mongo:6.0.4
    container_name: nestjs_mongo
    ports:
      - 27018:27017
    volumes:
      - ./scripts/event-store-mongoinit.js:/docker-entrypoint-initdb.d/event-store-mongoinit.js:ro
    environment:
      - MONGODB_DATABASE=event-store
    command: mongod --replSet event-store-repl-set

volumes:
  postgres-data:
