## spin up postgres 
version: "3.8"

services:
  db:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5436:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
