version: "3.8"

services:
  notification-svc:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=notification-svc
    command: npm run start:dev -- notification-svc # This instructs Docker Compose to run the "start:dev" script when starting the container
    deploy:
      replicas: 3
    environment:
      # Here we specify the environment variables that will be passed to the container
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats

  generator:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=generator
    command: npm run start:dev -- generator
    environment:
      - NATS_URL=nats://nats:4222
      - POSTGRES_HOST=generator-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=generator
    depends_on:
      - notification-svc
      - nats
      - generator-db

  generator-db:
    image: postgres:13.2-alpine
    environment:
      # We need to make sure these environment variables match the ones we specified in the "generator" service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=generator
      
  nats:
    container_name: nats
    image: nats:2.2.2-alpine