up:
	docker compose up -d

up_build:
	docker compose up --build -d

down:
	docker compose down --remove-orphans --volumes

log2:
	docker compose logs -f notification-svc

log1:
	docker compose logs -f generator
