up:
	docker compose up -d

up_build:
	docker compose up --build -d

down:
	docker compose down --remove-orphans --volumes

log-notif:
	docker compose logs -f notification-svc

log-gen:
	docker compose logs -f generator
