version: "3.8"

services:
  comment-svc:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=comment-svc
    command: npm run start:dev -- comment-svc # This instructs Docker Compose to run the "start:dev" script when starting the container
    ports:
      - 3000:3000 # This instructs Docker Compose to map port 3000 on the host to port 3000 on the container
    environment:
      # Here we specify the environment variables that will be passed to the container
      - POSTGRES_HOST=comment-svc-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=comment
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      # This instructs Docker Compose to start the "comment-svc-db" container before starting the "comment-svc" container
      - comment-svc-db
      - rabbitmq
      - moderation-svc
      - notification-svc

  comment-svc-db:
    image: postgres:13.2-alpine
    environment:
      # We need to make sure these environment variables match the ones we specified in the "comment-svc" service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=comment

  moderation-svc:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=moderation-svc
    command: npm run start:dev -- moderation-svc
    deploy:
      replicas: 2
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq

  notification-svc:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=notification-svc
    command: npm run start:dev -- notification-svc
    deploy:
      replicas: 2
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672